= About

This site is authored in https://asciidoc.org[Asciidoc] and published using https://docs.antora.org[Antora].
Think of it as a small example of what I think makes a good documentation site.
For example, this content module is separate from the project that collects the content into a published site.
This module could, therefore, be reused in a different context.

== Documentation formats

I've used a pretty wide variety of formats for authoring technical documentation, starting off with unstructured Framemaker and moving on through SGML, DITA, restructedText, and more lately Markdown.

I tend to prefer semantic markup formats, and think https://en.wikipedia.org/wiki/WYSIWYM[WYSIWYM] is the best paradigm for technical communicators.
But I also understand the appeal of simple, broadly implemented formats like Markdown, even if I don't actually love Markdown itself--I find it makes for a clumsy authoring experience.

Asciidoc is similar enough to Markdown to make it relatively easy to adapt for people new to the format, but is a complete authoring format on its own.
It has most of the same strengths as Markdown--simple, lightweight, and readable markup--without the drawbacks: punting the difficult use-cases to raw HTML or non-standard extensions, multiple dialects with varying levels of support, no domain-specific syntax for technical communication, and an overemphasis on making the output look a certain way.
Asciidoc is not semantic markup, but it was originally designed as a format for technical communicators.

If you look at the https://github.com/shampeon/resume-component[source of this site], you will see that I'm using the https://asciidoctor.org/docs/asciidoc-recommended-practices/[Asciidoctor recommended best practices] for authoring in Asciidoc.
In particular, I'm using one sentence per line.
While it's not a common practice among tech writers, it really does make a lot of sense in a world where https://www.writethedocs.org/guide/docs-as-code/[docs as code] is the dominant paradigm.
Reviewing changes in a documentation pull request would be so much easier if everyone adopted one sentence per line.

With all that being said, I've been doing this for a long time, and I can adapt and work in most environments.
Reasonable people disagree about formats, workflows, style.
This is just an example of what I prefer at this stage of my career, based on my experience writing docs in many different contexts over the last 25 years.